// <auto-generated />
using System;
using BingoCompany.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BingoCompany.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BingoDbContext))]
    partial class BingoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bingo")
                .HasAnnotation("BingoCompany:WinningPatternsRevision", "2")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BingoCompany.Domain.Models.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "OccurredAt");

                    b.ToTable("AuditEntries", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacementCardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.ToTable("Cards", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardsPerParticipant")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarkingMode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.ToTable("Events", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DrawSequence")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SequenceHash")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Rounds", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.CardMark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("DrawSequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "CardId", "Number")
                        .IsUnique();

                    b.ToTable("CardMarks", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.DrawnNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("DrawnNumbers", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeRegistration")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleEmployeeName")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Participants", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.PrizeStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWinnerPresentationClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("Pattern")
                        .HasColumnType("integer");

                    b.Property<string>("PrizeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("PrizeStages", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.RoundEligibleCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IncludedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "CardId")
                        .IsUnique();

                    b.ToTable("RoundEligibleCards", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.RoundWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrawSequence")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TieBreakerNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId", "CardId")
                        .IsUnique();

                    b.ToTable("RoundWinners", "bingo");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoCard", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoEvent", null)
                        .WithMany("Cards")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoRound", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoEvent", null)
                        .WithMany("Rounds")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.DrawnNumber", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoRound", null)
                        .WithMany("DrawnNumbers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.Participant", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoEvent", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.PrizeStage", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoRound", null)
                        .WithMany("Stages")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.RoundEligibleCard", b =>
                {
                    b.HasOne("BingoCompany.Domain.Models.BingoRound", null)
                        .WithMany("EligibleCards")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoEvent", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("BingoCompany.Domain.Models.BingoRound", b =>
                {
                    b.Navigation("DrawnNumbers");

                    b.Navigation("EligibleCards");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
